-- ============================================================
-- schema.sql · 建表脚本（Day 16｜2026-10-05）
-- 项目：个人主页（王畅达）
-- 数据库：腾讯云 CloudBase · SQL 型数据库（PostgreSQL）
-- 依据：api-contract.md（登录/账号、分享列表、数据读写接口）
--        + PRD.md 第八节（登录与管理后台设计）
--        + data.js（分享区四板块：涂鸦/随笔/合影/资源）
--
-- 本脚本可重复执行：先 DROP 再 CREATE，重跑不报错、不残留旧表。
--
-- 为什么选 PostgreSQL（而不是之前设想的 MySQL）？
--   CloudBase 体验版控制台提供的「SQL 型数据库」实际是 PostgreSQL
--   （控制台标题：PostgreSQL 管理，自带 REST API / RLS 策略），
--   所以建表语法按 PostgreSQL 编写，与 MySQL 的主要差异：
--   ① 自增主键用 GENERATED BY DEFAULT AS IDENTITY（MySQL 用 AUTO_INCREMENT）
--   ② 字段注释用 COMMENT ON 语句（MySQL 用行内 COMMENT）
--   ③ 无 UNSIGNED / ENGINE / CHARSET 子句（默认 UTF8）
--   ④ desc 是保留字，列名改用 description
-- ============================================================

-- 先删子表（works 的外键依赖 users），再删父表
DROP TABLE IF EXISTS "works";
DROP TABLE IF EXISTS "users";

-- ------------------------------------------------------------
-- 表 1：users（账号表）
-- 存什么：登录凭据——谁可以登录后台、用什么账号密码。
-- 角色：这是「一」的一方，一个账号可以有多条作品。
-- ------------------------------------------------------------
CREATE TABLE "users" (
  -- 主键：自增长整数（IDENTITY 是 PostgreSQL 标准自增写法）。
  -- BY DEFAULT = 平时自动生成，也允许脚本显式指定 id（种子数据需要）。
  -- 选 BIGINT 而非 INT：虽然现在只有 1 个账号，但 BIGINT 一劳永逸，不必担心溢出。
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 登录用户名。VARCHAR(32)：自定义短用户名足够；UNIQUE 保证不重复。
  "username" VARCHAR(32) NOT NULL UNIQUE,

  -- 密码哈希（加盐），绝不存明文！VARCHAR(255)：bcrypt 等算法输出约 60~72 字符，
  -- 留足长度，以后换哈希算法不用改表。
  "password_hash" VARCHAR(255) NOT NULL,

  -- 创建时间。TIMESTAMP 存「年月日时分秒」；DEFAULT now() 让数据库自动填当前时间。
  "created_at" TIMESTAMP NOT NULL DEFAULT now()
);

-- 字段注释（PostgreSQL 用单独的 COMMENT ON 语句，控制台悬停字段可见）
COMMENT ON TABLE  "users"                IS '登录账号表（仅用户本人一个账号）';
COMMENT ON COLUMN "users"."id"           IS '用户主键，自增';
COMMENT ON COLUMN "users"."username"     IS '登录用户名（唯一，不开放注册）';
COMMENT ON COLUMN "users"."password_hash" IS '密码哈希（加盐，绝不存明文）';
COMMENT ON COLUMN "users"."created_at"   IS '账号创建时间';

-- ------------------------------------------------------------
-- 表 2：works（作品表）
-- 存什么：分享区四个板块的作品，用 category 字段区分板块。
-- 角色：这是「多」的一方，user_id 指向 users.id（外键关联）。
-- ------------------------------------------------------------
CREATE TABLE "works" (
  -- 主键：自增长整数，同 users.id。
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- ★ 关联字段：作品属于哪个账号。外键指向 users.id——
  --   这就是两张表「靠哪个字段关联」的答案：works.user_id → users.id。
  --   ON DELETE CASCADE：删除账号时，其名下作品一并删除（保持数据一致）。
  "user_id" BIGINT NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE,

  -- 板块分类。VARCHAR(16) 存英文标识（doodle/essay/photo/resource）：
  -- 比存中文稳定省空间，前端筛选按这个值匹配。
  "category" VARCHAR(16) NOT NULL,

  -- 标题。VARCHAR(120)：分享标题不会太长，120 够用且有约束力。
  "title" VARCHAR(120) NOT NULL,

  -- 简介/说明。注意：desc 是 SQL 保留字（ORDER BY ... DESC），不能直接做列名，
  -- 故改名 description；接口层（Day 17）再映射回前端的 desc 字段。
  -- 用 TEXT：随笔可能写好几段，TEXT 不限长度（PostgreSQL 的 TEXT 和 VARCHAR 性能相同）。
  "description" TEXT,

  -- 图片文件名。涂鸦/随笔/合影用；资源类为 NULL。
  -- 存文件名（img-hand.jpg）而非完整 URL：图片路径由前端拼接，以后换域名不用改数据。
  "img" VARCHAR(255),

  -- 外链网址。仅资源板块使用，其余为 NULL。VARCHAR(2048)：URL 可能很长，2048 是保守上限。
  "link" VARCHAR(2048),

  -- 可见性状态，对应 PRD 8.2「隐藏 vs 删除」：
  --   public = 公开（进分享列表）；hidden = 隐藏（仍存库，前台不显示，可恢复）。
  --   「删除」是物理移除整行，不靠状态字段表达。
  "status" VARCHAR(8) NOT NULL DEFAULT 'public',

  -- 发布时间。
  "created_at" TIMESTAMP NOT NULL DEFAULT now()
);

-- 索引：加速两类高频查询（按作者查作品 / 按板块筛选）
CREATE INDEX "idx_works_user"     ON "works" ("user_id");
CREATE INDEX "idx_works_category" ON "works" ("category");

-- 字段注释
COMMENT ON TABLE  "works"              IS '分享区作品表（涂鸦/随笔/合影/资源四板块统一存一张表）';
COMMENT ON COLUMN "works"."id"         IS '作品主键，自增';
COMMENT ON COLUMN "works"."user_id"    IS '所属账号（外键 → users.id）★两表关联字段';
COMMENT ON COLUMN "works"."category"   IS '板块：doodle涂鸦/essay随笔/photo合影/resource资源';
COMMENT ON COLUMN "works"."title"      IS '作品标题';
COMMENT ON COLUMN "works"."description" IS '作品简介（随笔为正文，可较长）';
COMMENT ON COLUMN "works"."img"        IS '图片文件名（涂鸦/随笔/合影用，资源类可空）';
COMMENT ON COLUMN "works"."link"       IS '外链网址（仅资源板块使用，其余为 NULL）';
COMMENT ON COLUMN "works"."status"     IS '可见性：public公开/hidden隐藏';
COMMENT ON COLUMN "works"."created_at" IS '作品发布时间';
